Make the life of Debian users more easy When running an official Debian kernel, you don't have to recompile it anymore. We can patch the kernel for you.

diff --git a/contrib/sasc-ng/configure b/contrib/sasc-ng/configure
--- a/contrib/sasc-ng/configure
+++ b/contrib/sasc-ng/configure
@@ -1,9 +1,27 @@
 #!/bin/sh
 
+die(){
+    echo $1
+    exit 1
+}
+
 die_unknown(){
     echo "Unknown option \"$1\"."
     echo "See $0 --help for available options."
     exit 1
+}
+
+confirm(){
+    # call with a prompt string or use a default
+    read -r -p "${1:-Are you sure? [y/N]} " response
+    case $response in
+        [yY][eE][sS]|[yY]) 
+            true
+            ;;
+        *)
+            false
+            ;;
+    esac
 }
 
 #check whether option is supported by this cpu
@@ -22,7 +40,7 @@ check_cpu(){
 }
 
 #try to figure out best FFdecsa compiler options
-get_cpu_optimization() {
+get_cpu_optimization(){
    FLAGS="FLAGS=-O3 -fexpensive-optimizations -funroll-loops"
    arch=`uname -m`
    processors_flags=`cat /proc/cpuinfo | grep "flags" | head -n 1`
@@ -61,7 +79,7 @@ get_cpu_optimization() {
    echo "Processor capabilities: $ARCH ($OPTS )"
 }
 
-show_help() {
+show_help(){
   echo "Usage: configure [options]"
   echo "Options: [defaults in brackets after descriptions]"
   echo
@@ -122,17 +140,113 @@ done
     SECOND_DIGIT=$( echo `uname -r` | grep -o '[[:digit:]]\+' | head -n2 | awk 'NR==2' )
     PATCHLEVEL=$( echo `uname -r` | grep -o '[[:digit:]]\+' | head -n3 | awk 'NR==3' )
 
-# If running kernel is < 2.6.38 abort
+# Get OS and release info
+
+    OS=$( lsb_release -si )
+    RELEASE=$( lsb_release -sc )
+
+# Abort if running kernel is < 2.6.38
+
 if [ $FIRST_DIGIT -eq 2 ]; then
   if [ $SECOND_DIGIT -lt 6 ]; then
-    echo -e "The kernel you are running is not supported anymore.\n\nMinimum supported version is 2.6.38\n\nAborting..."
+    echo "The kernel you are running is not supported anymore.\n\nMinimum supported version is 2.6.38\n\nAborting..."
     exit 1
-    if [ $SECOND_DIGIT -eq 6 ]; then
-      if [ $PATCHLEVEL -lt 38 ]; then
-        echo -e "The kernel you are running is not supported anymore.\n\nMinimum supported version is 2.6.38\n\nAborting..."
-        exit 1
-      fi
+  elif [ $SECOND_DIGIT -eq 6 ]; then
+    if [ $PATCHLEVEL -lt 38 ]; then
+      echo "The kernel you are running is not supported anymore.\n\nMinimum supported version is 2.6.38\n\nAborting..."
+      exit 1
     fi
+  fi
+fi
+
+# Are we running Debian?
+# If so, make our lives easier!
+
+if echo $OS | grep 'Debian' 2>&1 1>/dev/null; then
+
+# Install dependencies
+
+  if ! dpkg-query -l libv4l-dev > /dev/null 2>&1; then
+     echo "Missing libv4l-dev, marking for installation."
+     apt-get install libv4l-dev -y || die "Error installing libv4l-dev"
+  fi
+
+  if ! dpkg-query -l libproc-processtable-perl > /dev/null 2>&1; then
+     echo "Missing libproc-processtable-perl, marking for installation."
+     apt-get install libproc-processtable-perl -y || die "Error installing libproc-processtable-perl"
+  fi
+
+  if ! dpkg-query -l libssl-dev > /dev/null 2>&1; then
+     echo "Missing libssl-dev, marking for installation."
+     apt-get install libssl-dev -y || die "Error installing libssl-dev"
+  fi
+
+  if ! dpkg-query -l linux-headers-`uname -r` > /dev/null 2>&1; then
+     echo "\nMissing linux-headers-`uname -r`, marking for installation.\n\n
+     IMPORTANT: If you compiled a custom kernel, answer no\n"
+     confirm "Would you really like me to install linux-headers-`uname -r`? [y/N]"
+    # if answer = no
+    if [ $(echo $?) -eq 1 ]; then
+      echo "\n   Not installing linux-headers-`uname -r`\n" 
+    # if answer = yes
+    else
+       apt-get install linux-headers-`uname -r` -y
+    fi
+  fi
+
+  # When using sasc, the kernel has to be patched.
+  # Let's do it.
+
+    KERNEL_TARBALL="/usr/src/linux-source-$SHORT_KERNEL.tar.bz2"
+    BUILD_DIR=/lib/modules/`uname -r`/build
+    TEMPDIR=/usr/src/sasctmp/$SHORT_KERNEL
+
+  echo "\nSasc needs a patched dvb-core.ko kernel module.\n\nIf you are running a default Debian kernel, I can do that for you.\nIn order to do this right, you need a line like:\n\n deb-src http://ftp.debian.org/debian/ wheezy main contrib non-free\n\nin your /etc/apt/sources.list and do apt-get update afterwards.\n\n(or if you are running a kernel from eg 'sid' replace \n'wheezy' with 'sid' in that line)\n\n"
+  confirm "Is your sources.list OK and do you want me to install linux-source-$SHORT_KERNEL? This will remove any previously installed linux-source packages and (re)install the source for your current kernel. Having done that, your running kernel will be patched for use with sasc.[y/N]"
+
+  if [ $(echo $?) -eq 1 ]; then
+    echo "\n   Not installing linux-source-$SHORT_KERNEL\n" 
+  else
+   apt-get purge linux-source* -y && apt-get install linux-source-$SHORT_KERNEL -y
+   echo "\nBuilding patched dvb-core module for kernel `uname -r`\n\nPreparing, this may take a while...\n"
+   rm -rf $TEMPDIR
+   mkdir -p $TEMPDIR
+     if  [ $FIRST_DIGIT -eq 3 ]; then
+        if [ $SECOND_DIGIT -lt 7 ]; then
+          tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 5 linux-source-$SHORT_KERNEL/drivers/media/dvb/dvb-core/
+          echo "\nBuilding and installing, please be patient...\n"
+	      patch -p5 -d $TEMPDIR < linux-2.6.38-dvb-mutex.patch > /dev/null 2>&1
+          make -C $BUILD_DIR M=$TEMPDIR modules
+          rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
+          mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
+          /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/
+          cp -f $TEMPDIR/dvbdev.h dvbloopback/module/dvbdev-orig.h
+          rm -rf $TEMPDIR
+          depmod -a
+        else 
+          tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
+          echo "\nBuilding and installing, please be patient...\n"
+	      patch -p4 -d $TEMPDIR < linux-3.7.1-dvb-mutex.patch > /dev/null 2>&1
+          make -C $BUILD_DIR M=$TEMPDIR/dvb-core modules
+          rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
+          mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
+          /usr/bin/install $TEMPDIR/dvb-core/dvb-core.ko /lib/modules/`uname -r`/updates/
+          cp -f $TEMPDIR/dvb-core/dvbdev.h dvbloopback/module/dvbdev-orig.h
+          rm -rf $TEMPDIR
+          depmod -a
+        fi
+     elif [ $FIRST_DIGIT -eq 2 ]; then
+        tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 5 linux-source-$SHORT_KERNEL/drivers/media/dvb/dvb-core/
+        echo "\nBuilding and installing, please be patient...\n"
+        patch -p5 -d $TEMPDIR < linux-2.6.38-dvb-mutex.patch > /dev/null 2>&1
+        make -C $BUILD_DIR M=$TEMPDIR modules
+        rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
+        mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
+        /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/
+        cp -f $TEMPDIR/dvbdev.h dvbloopback/module/dvbdev-orig.h
+        rm -rf $TEMPDIR
+        depmod -a
+     fi
   fi
 fi
 
