Rework kernel patching

diff --git a/contrib/sasc-ng/configure b/contrib/sasc-ng/configure
--- a/contrib/sasc-ng/configure
+++ b/contrib/sasc-ng/configure
@@ -148,8 +148,8 @@ done
 # Abort if running kernel is < 3.x
 
 if [ $FIRST_DIGIT -lt 3 ]; then
-  echo "The kernel you are running is not supported anymore.\n\nMinimum supported version is 3.x\n\nAborting..."
-    exit 1
+  echo "The kernel you are running is not supported anymore.\n\nMinimum supported version is 2.6.38\n\nAborting..."
+  exit 1
 fi
 
 # Are we running Debian?
@@ -177,7 +177,7 @@ if echo $OS | grep 'Debian' 2>&1 1>/dev/null; then
   if ! dpkg-query -l linux-headers-`uname -r` > /dev/null 2>&1; then
      echo "\nMissing linux-headers-`uname -r`, marking for installation.\n\n
      IMPORTANT: If you compiled a custom kernel, answer no\n"
-     confirm "Would you like me to install linux-headers-`uname -r`? [y/N]"
+     confirm "Would you really like me to install linux-headers-`uname -r`? [y/N]"
     # if answer = no
     if [ $(echo $?) -eq 1 ]; then
       echo "\n   Not installing linux-headers-`uname -r`\n" 
@@ -197,76 +197,73 @@ if echo $OS | grep 'Debian' 2>&1 1>/dev/null; then
   echo "\nSasc needs a patched dvb-core.ko kernel module.\n\nIf you are running a default Debian kernel, or if you compiled a kernel from www.kernel.org, I can do that for you.\nIn order to do this right, you need a line like:\n\n deb-src http://ftp.debian.org/debian/ wheezy main contrib non-free\n\nin your /etc/apt/sources.list and do apt-get update afterwards.\n\n(or if you are running a kernel from eg 'sid' replace \n'wheezy' with 'sid' in that line)\n\nOr if you compiled a kernel from www.kernel.org, just answer no.\nWe'll address this situation in a next question.\n\n"
   confirm "Is your sources.list OK and do you want me to install linux-source-$SHORT_KERNEL? This will remove any previously installed linux-source packages and (re)install the source for your current kernel. Having done that, your running kernel will be patched for use with sasc.[y/N]"
 
-    if [ $(echo $?) -eq 1 ]; then
-      echo "\n   Not installing linux-source-$SHORT_KERNEL\n"
-      confirm "Do you want me to patch a kernel that you compiled from official www.kernel.org sources? [y/N]"
-      if [ $(echo $?) -eq 1 ]; then
-        echo "\n   Not patching any kernel\n"
-      else
-        if [ $FIRST_DIGIT -eq 3 ]; then
-          wget -P /usr/src https://www.kernel.org/pub/linux/kernel/v3.x/linux-$SHORT_KERNEL.tar.bz2
-        fi
-      fi
-        echo "\nBuilding patched dvb-core module for kernel `uname -r`\n\nPreparing, this may take a while...\n"
-        rm -rf $TEMPDIR
-        mkdir -p $TEMPDIR
-      if  [ $FIRST_DIGIT -eq 3 ]; then
-         if [ $SECOND_DIGIT -lt 7 ]; then
-           tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 5 linux-source-$SHORT_KERNEL/drivers/media/dvb/dvb-core/
-           echo "\nBuilding and installing, please be patient...\n"
-           patch -p5 -d $TEMPDIR < linux-2.6.38-dvb-mutex.patch > /dev/null 2>&1
-           make -C $BUILD_DIR M=$TEMPDIR modules
-           rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
-           mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
-           /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/
-           cp -f $TEMPDIR/dvbdev.h dvbloopback/module/dvbdev-orig.h
-           rm -rf $TEMPDIR
-           depmod -a
-         else 
-           tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
-           echo "\nBuilding and installing, please be patient...\n"
-           patch -p4 -d $TEMPDIR < linux-3.7.1-dvb-mutex.patch > /dev/null 2>&1
-           make -C $BUILD_DIR M=$TEMPDIR/dvb-core modules
-           rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
-           mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
-           /usr/bin/install $TEMPDIR/dvb-core/dvb-core.ko /lib/modules/`uname -r`/updates/
-           cp -f $TEMPDIR/dvb-core/dvbdev.h dvbloopback/module/dvbdev-orig.h
-           rm -rf $TEMPDIR
-           depmod -a
-         fi
-      fi
-    fi
-  else
+  if [ $(echo $?) -eq 0 ]; then
     apt-get purge linux-source* -y && apt-get install linux-source-$SHORT_KERNEL -y
     echo "\nBuilding patched dvb-core module for kernel `uname -r`\n\nPreparing, this may take a while...\n"
     rm -rf $TEMPDIR
     mkdir -p $TEMPDIR
-      if  [ $FIRST_DIGIT -eq 3 ]; then
-        if [ $SECOND_DIGIT -lt 7 ]; then
-          tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 5 linux-source-$SHORT_KERNEL/drivers/media/dvb/dvb-core/
-          echo "\nBuilding and installing, please be patient...\n"
-          patch -p5 -d $TEMPDIR < linux-2.6.38-dvb-mutex.patch > /dev/null 2>&1
-          make -C $BUILD_DIR M=$TEMPDIR modules
-          rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
-          mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
-          /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/
-          cp -f $TEMPDIR/dvbdev.h dvbloopback/module/dvbdev-orig.h
-          rm -rf $TEMPDIR
-          depmod -a
-        else 
-          tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
-          echo "\nBuilding and installing, please be patient...\n"
-          patch -p4 -d $TEMPDIR < linux-3.7.1-dvb-mutex.patch > /dev/null 2>&1
-          make -C $BUILD_DIR M=$TEMPDIR/dvb-core modules
-          rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
-          mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
-          /usr/bin/install $TEMPDIR/dvb-core/dvb-core.ko /lib/modules/`uname -r`/updates/
-          cp -f $TEMPDIR/dvb-core/dvbdev.h dvbloopback/module/dvbdev-orig.h
-          rm -rf $TEMPDIR
-          depmod -a
-        fi
-     fi
-   fi
+    if  [ $FIRST_DIGIT -eq 3 ]; then
+      if [ $SECOND_DIGIT -lt 7 ]; then
+        tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 5 linux-source-$SHORT_KERNEL/drivers/media/dvb/dvb-core/
+        echo "\nBuilding and installing, please be patient...\n"
+        patch -p5 -d $TEMPDIR < linux-2.6.38-dvb-mutex.patch > /dev/null 2>&1
+        make -C $BUILD_DIR M=$TEMPDIR modules
+        rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
+        mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
+        /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/
+        cp -f $TEMPDIR/dvbdev.h dvbloopback/module/dvbdev-orig.h
+        rm -rf $TEMPDIR
+        depmod -a
+      else 
+        tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
+        echo "\nBuilding and installing, please be patient...\n"
+        patch -p4 -d $TEMPDIR < linux-3.7.1-dvb-mutex.patch > /dev/null 2>&1
+        make -C $BUILD_DIR M=$TEMPDIR/dvb-core modules
+        rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
+        mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
+        /usr/bin/install $TEMPDIR/dvb-core/dvb-core.ko /lib/modules/`uname -r`/updates/
+        cp -f $TEMPDIR/dvb-core/dvbdev.h dvbloopback/module/dvbdev-orig.h
+        rm -rf $TEMPDIR
+        depmod -a
+      fi
+    fi
+  else
+    echo "\n   Not installing linux-source-$SHORT_KERNEL\n"  
+    confirm "Do you want me to patch a kernel that you compiled from official www.kernel.org sources?[y/N]"
+    if [ $(echo $?) -eq 0 ]; then
+      if [ $FIRST_DIGIT -eq 3 ]; then
+        wget -P /usr/src https://www.kernel.org/pub/linux/kernel/v3.x/linux-$SHORT_KERNEL.tar.bz2
+      fi
+      echo "\nBuilding patched dvb-core module for kernel `uname -r`\n\nPreparing, this may take a while...\n"
+      rm -rf $TEMPDIR
+      mkdir -p $TEMPDIR
+      if [ $SECOND_DIGIT -lt 7 ]; then
+        tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 5 linux-source-$SHORT_KERNEL/drivers/media/dvb/dvb-core/
+        echo "\nBuilding and installing, please be patient...\n"
+        patch -p5 -d $TEMPDIR < linux-2.6.38-dvb-mutex.patch > /dev/null 2>&1
+        make -C $BUILD_DIR M=$TEMPDIR modules
+        rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
+        mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
+        /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/
+        cp -f $TEMPDIR/dvbdev.h dvbloopback/module/dvbdev-orig.h
+        rm -rf $TEMPDIR
+        depmod -a
+      else 
+        tar -xjf $KERNEL_TARBALL -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
+        echo "\nBuilding and installing, please be patient...\n"
+        patch -p4 -d $TEMPDIR < linux-3.7.1-dvb-mutex.patch > /dev/null 2>&1
+        make -C $BUILD_DIR M=$TEMPDIR/dvb-core modules
+        rm -f /lib/modules/`uname -r`/updates/dvb-core.ko > /dev/null 2>&1
+        mkdir -p /lib/modules/`uname -r`/updates > /dev/null 2>&1
+        /usr/bin/install $TEMPDIR/dvb-core/dvb-core.ko /lib/modules/`uname -r`/updates/
+        cp -f $TEMPDIR/dvb-core/dvbdev.h dvbloopback/module/dvbdev-orig.h
+        rm -rf $TEMPDIR
+        depmod -a
+      fi
+    else
+      echo "\n   Not patching any kernel\n"
+    fi
+  fi
 fi
 
 if test "x$CXX" = "x"; then
@@ -402,6 +399,11 @@ if test "x$dvb_path" = "x"; then
     else
       echo "`uname -r` kernel detected."
       cp -f dvbloopback/module/config_dvb_new.pl dvbloopback/module/config_dvb.pl
+    fi
+  else
+    if [ $FIRST_DIGIT -eq 2 ]; then
+      echo "`uname -r` kernel detected."
+      cp -f dvbloopback/module/config_dvb_old.pl dvbloopback/module/config_dvb.pl
     fi
   fi
 fi
